core:
  server-prefix: '&8▍ &9&lServer &r&8≫ &r'
  no-permission: '&r&cYou don''t have permission to use this command.'
  chat-format: '&8▍ &7%player% &r&8≫ &r%message%'
  join-format: '&a▶ %player% joined the server'
  quit-format: '&c◀ %player% left the server'
  disallowed-commands:
    - 'bukkit:?'
    - 'bukkit:about'
    - 'bukkit:help'
    - 'bukkit:pl'
    - 'bukkit:plugins'
    - 'bukkit:reload'
    - 'bukkit:rl'
    - 'bukkit:timings'
    - 'bukkit:ver'
    - 'bukkit:version'
    - '?'
    - 'about'
    - 'help'
    - 'pl'
    - 'plugins'
    - 'reload'
    - 'rl'
    - 'timings'
    - 'ver'
    - 'version'
    - 'bungee'
    - 'icanhasbukkit'
    - 'list'
    - 'lp'
    - 'luckperms'
    - 'perm'
    - 'permission'
    - 'permissions'
    - 'perms'
    - 'luckperms:lp'
    - 'luckperms:luckperms'
    - 'luckperms:perm'
    - 'luckperms:permission'
    - 'luckperms:permissions'
    - 'luckperms:perms'
activity:
  enabled: false
  discord-webhook-url: 'https://discord.com/api/webhooks/'
vanish:
  others:
    no-permission: '&cYou don''t have permission to vanish other players.'
    vanish-player: '%player% is now &avanished&r.'
    show-player: '%player% is now &cvisible&r again.'
  vanish-player: 'You are now &avanished&r.'
  show-player: 'You are now &cvisible&r again.'
  player-not-found: '&cThe specified player is not online.'