core:
  server-prefix: '&8▍ &9&lServer &r&8≫ &r'
  no-permission: '&r&cYou don''t have permission to use this command.'
vanish:
  others:
    no-permission: '&cYou don''t have permission to vanish other players.'
    vanish-player: '%player% is now &avanished&r.'
    show-player: '%player% is now &cvisible&r again.'
  vanish-player: 'You are now &avanished&r.'
  show-player: 'You are now &cvisible&r again.'
  player-not-found: '&cThe specified player is not online.'